name: synapp_functions_helper
description: A helper with many helpful functions for developing appwrite functions
version: 1.0.4
# homepage: https://www.example.com
repository: https://github.com/krikristoophe/appwrite_functions_helper

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: 6.5.4
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dart_appwrite: ^7.2.0
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: 4.7.0
  mailer: ^6.0.0
